name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21.x

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test
      run: |
        go test ./... -coverprofile=profile.cov

    - uses: shogo82148/actions-goveralls@v1.9.1
      with:
        path-to-profile: profile.cov
